#+TITLE: Notes
* Email
- 'Mina bevakningar' heading and subheading are in an image rather than displayed in text on the email.
  This isn't a huge deal but I couldn't translate the text because of this.
- On larger screens, the 'Unsubscribe' and 'Manage Email Preferences' buttons on the first email are aligned to the left. They should probably be aligned directly below the note that allows users to unsubscribe.
If the translations are correct, then all of the text is good!
* Admin Website (Mufasa)
- Registering as an admin is currently broken (I couldn't get it to work on the development site; received a 'NoSuchFlow' error when clicking on the link).
- The formatting tool (prettier) demands lots of double quotes when single quotes are primarily used throughout the code.
- The README could use a lot more information about the organization of the tool!
- Admin portal should probably validate inputs when creating a campaign internally.
- 'misuse of the recommended sameSite attribute'
- Cookie “SIDCC” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
- UX :: not clear that the different parts of each form are clickable and direct to different forms.
- UI Error :: When in mobile mode, if the hamburger menu is pressed, then the user logs out, after logging in they no longer have the 'X' to close the hamburger menu visible.
- UI :: On mobile, should be able to click the 'Skira Admin' header to go back to the main page.
- UI :: On mobile I should still have access to the drop-down with the contact information.
- Buttons for replacing information should probably have 'X's so that the inputs can be closed without changing any of the information. Will save any crazy errors from accidental clicks.
- Currently undefined URLs go to the main page.
  For more clear communication, it would be a good idea to create a dedicated 404
  to ensure that end users understand that this route is invalid rather than obscuring the failure.
 
** App Structure
Main ->
- GraphQL (Apollo Provider)
  - /data :: manages API calls to GraphQL
- Redux (Provider)
  - /state :: Redux state
    - /actions :: Redux Actions
    - /reducers :: Redux reducers
    - /sagas :: Saga middleware. handles requests. dispatches to /api
- Router - React Router support
- Main
  -
- /lang :: Contains data definitions for all of the strings used throughout the program.
  This is used to a great extent by i18n; it exports all of the translation features.
  - /routes :: contains strings to route to every component.
    - /contact :: contact information for different companies and users
    - /product :: all of the current products
      - /{id} :: the product ID
      - /list :: a list of all of the products
    - /company :: all of the companies registered for the service
      - /item/{id} :: an individual company
    - /register :: invite a user to register.
      approve them manually with the organization number or invite them to apply
      by providing their email address.
    - /campaign :: create a campaign here
    - /users :: The main page; an overview of the user statistics
    - /trade :: the view for trading items. can reload and sort with different parameters.
    - /sign :: currently just goes to '/'
    - /messages :: undefined
    - /sale :: undefined
    - /devtools :: has a button that doesn't work! 'maintenance.tasks is not a function'
- /resources :: images and fonts.
- /routes :: a file with a basic configuration for at the root of the site that
  ensures that the current user is an administrator
- /utils :: various utility scripts for the platform:
  - auth :: manages auth cookies
  - constants :: defines response time, owner min and max percentage,
    and ordering of quality display.
    - TODO: why is this stuff not in an array? Seems less useful in an object.
  - hooks :: hooks for working with partial state, determining whether something is a function, etc...
    index has a lot of random stuff, like getting the primary item in an array
  - general ::
    - roundCash line 137 seems to convert to a string to compare to another string? what??
  - parsing :: parsing activity data into discrete information.
  - sort :: utilities for sorting arrays by column, etc.
  - /validation :: tools for validating data
    - bank :: tools for validating bank data.
      takes into account several different variables
- /components :: react components used in several places on the site
  - AccordionTable :: an expanding, responsive, scrolling table
    includes action button, header column, etc.
    Has lots of cool settings for adjusting the behavior, generating a panel, etc. etc.
    Also includes filter buttons to apply filters to the loading table.
  - ActionButton :: has lots of fancy styles, but it's really just a button. can be disabled, configured to load, given a class name, color, etc.
  - ActionModal :: Opens a modal with actions. Just used for login now.
  - ActivityFeed :: The feed for different activities available on the platform.
    Used to display different activities currently occuring on the platform.
  - CompanyBillingddress ::


* Server (Pumbaa)
- 2:03:08 PM - error: BaseResolver ERROR requiresUserPrivileges: occurs when logging in to the client website. This occurs when logging into

* Learning Tech Stack
- Redux
  - [[https://github.com/redux-saga/redux-saga][Saga Middleware]] :: A replacement for Redux Thunks; a separate thread in the application responsible for side effects such as requests.
    This uses [[https://github.com/gajus/gajus.com-blog/blob/master/posts/the-definitive-guide-to-the-javascript-generators/index.md][Generators]] under the hood.

    [[https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html][This tutorial]] is something I've found helpful.
    [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield][Generators]]
- GraphQL
* Admin Login
niklas@skira.se
password 'secret'
