#+TITLE: Lorri Node
This is a Nix development environment used to work on Node.js projects.

It's designed to be used with [[https://direnv.net][direnv]] and [[https://github.com/target/lorri][lorri]] to automatically configure and
load a development environment with nodejs and postgres available.

The following shell commands are exposed:
- startdb :: Starts the database.
- stopdb :: Stops the database.
- restart-db :: Restarts the database. Starts the database if it isn't currently running.
- reset-db :: Deletes the database and reinstantiates it.
- setup-db :: Sets up the postgres database.

* Installation
First install [[https://nixos.wiki/wiki/Nix_Installation_Guide][nix]], direnv and lorri with their respective instructions.

Then:
#+begin_src sh
cd lorri-node
direnv allow
install-deps
#+end_src

You should see direnv load several environment variables.
Unfortunately, as lorri does not properly support changing environment variables
from the 'shell.nix' configuration, they have to be set in direnv.
This means that you will not have access to any convenience functions when
entering the environment using 'lorri shell'.

Unfortunately, Nix is only currently supported on MacOS and Linux with no plans
to support Windows in the future. I highly recommend using Windows Subsystem for
Linux for development regardless and that is readily compatible.

* Configuration
The system assumes a simple database configuration with a single user and
database. The name of the database as well as the username and password of the
user are defined as shell environment variables in '.envrc'.

Several editors support integration with direnv; you'll need to install your
editor's direnv compatible program to properly ensure that the right
dependencies are available to your editor as well.
