{
  # Pumbaa configuration
  DB_HOSTNAME = "";
  MAILGUN_API_KEY = "";
  MAILGUN_DOMAIN = "";
  SENDGRID_API_KEY = "";
  BLOCK_SENDGRID = "";
  LOCAL_EMAIL = "";
  AUTH_SIGNATURE_KEY = "";
  ALLABOLAG_KEY = "";
  BANKID_URL = "";
  BANKID_PW = "";
  SLACK_CUSTOMER_WEBHOOK = "";
  SLACK_PUMBAA_LOGGER_WEBHOOK = "";
  GOOGLE_API_KEY = "";
  GOOGLE_APPLICATION_CREDENTIALS = "";
  GCP_PROJECT_ID = "";
  BUCKET_SALES_ATTACHMENTS = "";
  BUCKET_AGREEMENTS = "";
  MY_ZONE_NAME = "";
  MY_CONTAINER_NAME = "";
  INTERCOM_SECRET_KEY = "";
  ACTIVATE_GQL_PLAYGROUND = "";
  SLACK_SKIRA_TEAM_ID = "";
  CALENDAR_SKIRA_GENERAL = "";
  CALENDAR_SERVICE_ACCOUNT = "";
  PUMBAA_VERSION = "";

  # Nala configuration
  DOMAIN = "";
  NODE_ENV = "";
  REACT_APP_GOOGLE_API_KEY = "";
  INTERCOM_APP_ID = "";
  HOTJAR_VERSION = "";
}
