#!/usr/bin/env zsh

# Add the necessary users to the database.
function create-db-users() {
    echo "${DB_PASSWORD} ${DB_PASSWORD}" | createuser -d -l ${DB_USERNAME}
    if [ $? -eq 0 ]; then
        echo "Added user ${DB_USERNAME} with password ${DB_PASSWORD}."
    else
        echo "Could not create the user ${DB_USERNAME}."
    fi
}

# Creates databases required by Pumbaa.
function create-dbs() {
    createdb ${DB_NAME}
    createdb ${TEST_DB_NAME}
}

# Initializes the database.
function init-db-structure() {
    if [ ! -d $PGHOST ]; then
    mkdir -p $PGHOST
    fi

    if [ ! -d $PGDATA ]; then
    echo 'Initializing postgresql database...'
    initdb $PGDATA --auth=trust >/dev/null
    fi

    restart-db
    create-db-users
    create-dbs
}

# resets the database configuration
function reset-db() {
    rm -rf $PGDATA
    rm -rf $PGHOST
    killall postgres
    init-db-structure
}

reset-db
