#!/usr/bin/env sh

# Initializes the database.
if [ ! -d $PGHOST ]; then
    mkdir -p $PGHOST

    if [ ! -d $PGDATA ]; then
        echo 'Initializing postgresql database...'
        initdb $PGDATA --auth=trust >/dev/null
    fi

    restart-db

    # Add the necessary users to the database.
    echo "${DB_PASSWORD} ${DB_PASSWORD}" | createuser -d -l ${DB_USERNAME}
    if [ $? -eq 0 ]; then
        echo "Added user ${DB_USERNAME} with password ${DB_PASSWORD}."
    else
        echo "Could not create the user ${DB_USERNAME}."
    fi

    # Creates databases required by Pumbaa.
    createdb ${DB_NAME}
    createdb ${TEST_DB_NAME}
else
    echo "The database likely already exists. Try running restart-db instead."
fi
